from TETrading.signal_events.signals.active_position_signal import ActivePositionsSignals
from TETrading.signal_events.signals.entry_signal import EntrySignals
from TETrading.signal_events.signals.exit_signal import ExitSignals


class SignalHandler:
    """
    Handles signals given by the trading system logic.

    TODO: Implement methods _execute_signals and __call__.
    """

    def __init__(self):
        self.__entry_signals = EntrySignals()
        self.__exit_signals = ExitSignals()
        self.__active_positions = ActivePositionsSignals()

    def handle_entry_signal(self, symbol, data_dict):
        """
        Calls the EntrySignals members add_signal_data method,
        passing it given symbol and data_dict.

        Parameters
        ----------
        :param symbol:
            'str' : The symbol/ticker of an asset.
        :param data_dict:
            'Dict' : Data to be handled by the EntrySignals member.
        """

        self.__entry_signals.add_signal_data(symbol, data_dict)

    def handle_active_position(self, symbol, data_dict):
        """
        Calls the ActivePositionsSignals members add_data method,
        passing it given symbol and data_dict.

        Parameters
        ----------
        :param symbol:
            'str' : The symbol/ticker of an asset.
        :param data_dict:
            'Dict' : Data to be handled by the ActivePositionsSignals
            member.
        """

        self.__active_positions.add_data(symbol, data_dict)

    def handle_exit_signal(self, symbol, data_dict):
        """
        Calls the ExitSignals members add_signal_data method,
        passing it given symbol and data_dict.

        Parameters
        ----------
        :param symbol:
            'str' : The symbol/ticker of an asset.
        :param data_dict:
            'Dict' : Data to be handled by the ExitSignals member.
        """

        self.__exit_signals.add_signal_data(symbol, data_dict)

    def _execute_signals(self):
        # TODO: Implement functionality to be able to connect to brokers
        #  and execute orders with the use of an 'ExecutionHandler' class.
        pass

    def add_pos_sizing_evaluation_data(self, evaluation_dict):
        """
        Adds the given evaluation data to ActivePositionsSignals and
        EntrySignals members by calling their add_evaluation_data
        methods.

        Parameters
        ----------
        :param evaluation_dict:
            'Dict' : A dict with evaluation data generated by a
            PositionSizer object.
        """

        self.__active_positions.add_evaluation_data(evaluation_dict)
        self.__entry_signals.add_evaluation_data(evaluation_dict)

    def __str__(self):
        return f'\n{self.__active_positions}\n\n{self.__entry_signals}\n\n{self.__exit_signals}'

    def __call__(self):
        """
        Execute signals.

        TODO: Fully implement the methods functionality.
        """

        self._execute_signals()
